---
abstract: 'Create your own Parameterizable Types.'
author:
  - 'John Napiorkowski, C<< <jjnapiork@cpan.org> >>'
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.29
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Parameterizable
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dump: 1.17
  Devel::PartialDump: 0.13
  Digest::MD5: 2.39
  Moose: 1.08
  MooseX::Types: 0.22
  Scalar::Util: 1.19
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/MooseX-Types-Parameterizable.git
version: 0.03
